stages:
       - codestyle
       - build

codestyle-job:
  stage: codestyle
  tags: [d06]
  script:
    - cd ./code-samples
    - clang-format -n *.c || exit 1

build-job:
  stage: build
  tags: [do6]
  script:
    - cd ./code-samples
    - make all
  artifacts:
    name: "exe_DO"
    expose_as: 'DO executable'
    paths:
      - ./code-samples/DO
    expire_in: 30 days
  needs: ["codestyle-job"]
