 stages:
        - build
        - test
        - deploy

job1:
  stage: build
  script:
    - echo "билд прошел"

job2:
  stage: test
  script:
    - echo "тест прошел"

job3:
  stage: deploy
  script:
    - echo "деплой прошел прошел"
